version: '2.4'
services:
  elastic-agent:
<<<<<<< HEAD
    image: docker.elastic.co/${elasticAgentDockerNamespace:-beats}/elastic-agent${elasticAgentDockerImageSuffix}:${elasticAgentTag:-7.14.0-SNAPSHOT}
    container_name:  ${elasticAgentContainerName}
=======
    image: "docker.elastic.co/${elasticAgentDockerNamespace:-beats}/elastic-agent${elasticAgentDockerImageSuffix}:${elasticAgentTag:-8.0.0-SNAPSHOT}"
>>>>>>> 787b976 (fix: apply container name to elastic-agent Docker services (#1336))
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
    environment:
      - "FLEET_SERVER_ENABLE=1"
      - "FLEET_SERVER_INSECURE_HTTP=1"
      - "ELASTIC_AGENT_CLOUD=1"
      - "APM_SERVER_PATH=/apm-legacy/apm-server/"
      - "STATE_PATH=/apm-legacy/elastic-agent/"
      - "CONFIG_PATH=/apm-legacy/config/"
      - "DATA_PATH=/apm-legacy/data/"
      - "LOGS_PATH=/apm-legacy/logs/"
      - "HOME_PATH=/apm-legacy/"
    platform: ${stackPlatform:-linux/amd64}
    volumes:
      - "${apmVolume}:/apm-legacy"
    ports:
      - "127.0.0.1:8220:8220"
      - "127.0.0.1:8200:8200"
      - "127.0.0.1:5066:5066"
