version: '2.4'
services:
  elastic-agent:
    image: docker.elastic.co/observability-ci/centos-systemd:latest
    container_name: ${centos_systemdContainerName}
    entrypoint: "/usr/sbin/init"
    platform: ${elasticAgentPlatform:-linux/amd64}
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro 
