repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-json
        exclude: ^notice/overrides.json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: check-xml
    -   id: end-of-file-fixer
        exclude: >
            (?x)^(
                cli/NOTICE.txt|
                e2e/NOTICE.txt
            )$

-   repo: git://github.com/dnephin/pre-commit-golang
    rev: v0.3.4
    hooks:
    -   id: go-fmt
    -   id: go-lint
    -   id: validate-toml
    -   id: no-go-testing
    -   id: go-critic

-   repo: git@github.com:elastic/apm-pipeline-library
    rev: current
    hooks:
    -   id: check-bash-syntax
    -   id: check-jenkins-pipelines
    -   id: check-unicode-non-breaking-spaces
    -   id: remove-unicode-non-breaking-spaces
    -   id: check-en-dashes
    -   id: remove-en-dashes
    -   id: check-jjbb
    -   id: check-gherkin-lint
        args: ["--disable", "AvoidOutlineForSingleExample,TooClumsy,TooLongStep,TooManyDifferentTags,TooManySteps"]
