repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-json
        exclude: ^notice/overrides.json
    -   id: check-merge-conflict
    -   id: check-yaml
        exclude: >
          (?x)^(internal/config/kubernetes.*)$
    -   id: check-xml
    -   id: end-of-file-fixer
        exclude: >
            (?x)^(
                cli/NOTICE.txt|
                e2e/NOTICE.txt|
                .stack-version
            )$

-   repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
    -   id: go-fmt
    -   id: no-go-testing
    -   id: golangci-lint
        args: ["--fix", "--fast", "--new"]

-   repo: https://github.com/elastic/apm-pipeline-library
    rev: current
    hooks:
    -   id: check-bash-syntax
    -   id: check-jenkins-pipelines
    -   id: check-unicode-non-breaking-spaces
        exclude: >
            (?x)^(
                .*/?\.*.(gif|jpg|png|tar.gz)
            )$
    -   id: remove-unicode-non-breaking-spaces
        exclude: >
            (?x)^(
                .*/?\.*.(gif|jpg|png|tar.gz)
            )$
    -   id: check-en-dashes
        exclude: >
            (?x)^(
                .*/?\.*.(tar.gz)
            )$
    -   id: remove-en-dashes
        exclude: >
            (?x)^(
                .*/?\.*.(tar.gz)
            )$
    -   id: check-gherkin-lint
        args: [
            "--disable", "AvoidOutlineForSingleExample,TooClumsy,TooManyTags,TooLongStep,TooManyDifferentTags,TooManySteps,UseBackground",
            "e2e/_suites/**/*.feature",
        ]
