version: '2.4'
services:
  elasticsearch:
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security=false
      - xpack.monitoring.collection.enabled=true
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=changeme
    image: "docker.elastic.co/observability-ci/elasticsearch:${elasticsearchTag:-8.6.2-7c4539d9-SNAPSHOT}"
    healthcheck:
        interval: 10s
        retries: 100
        test: ["CMD-SHELL", "curl -u admin:changeme -s http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=500ms"]
    platform: ${elasticsearchPlatform:-linux/amd64}
    ports:
      - "9200:9200"
      - "9300:9300"
