version: '2.4'
services:
  opbeans-go:
    environment:
      - ELASTIC_APM_APPLICATION_PACKAGES=co.elastic.apm.opbeans
      - ELASTIC_APM_JS_SERVER_URL=http://localhost:8000
      - ELASTIC_APM_SERVER_URL=http://localhost:8200
      - ELASTIC_APM_SERVICE_NAME=opbeans-go
      - ELASTIC_APM_LOG_FILE=stderr
      - ELASTIC_APM_LOG_LEVEL=debug
      - OPBEANS_SERVER_PORT=8000
    image: "docker.elastic.co/observability-ci/opbeans-go:${opbeansGoTag}"
    ports:
      - "8000:8000"
