version: '2.4'
services:
  debian:
    image: alehaa/debian-systemd:${debian_systemdTag:-stretch}
    container_name: ${debian_systemdContainerName} 
    entrypoint: "/sbin/init"
    privileged: true
    volumes:
      - ${debian_systemdAgentBinarySrcPath:-.}:${debian_systemdAgentBinaryTargetPath:-/tmp}
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
