version: '2.4'
services:
  elastic-agent:
    image: "docker.elastic.co/${elasticAgentDockerNamespace:-beats}/elastic-agent${elasticAgentDockerImageSuffix}:${elasticAgentTag:-8.0.0-SNAPSHOT}"
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
    environment:
      - "FLEET_SERVER_ENABLE=${fleetServerMode:-0}"
      - "FLEET_SERVER_INSECURE_HTTP=${fleetServerMode:-0}"
    platform: ${stackPlatform:-linux/amd64}
    ports:
      - "127.0.0.1:8220:8220"
