version: '2.4'
services:
  elastic-agent:
    image: docker.elastic.co/${elasticAgentDockerNamespace:-beats}/elastic-agent${elasticAgentDockerImageSuffix}:${elasticAgentTag:-7.10-SNAPSHOT}
    container_name: ${elasticAgentContainerName}
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
    environment:
      - "KIBANA_HOST=http://${kibanaHost:-kibana}:${kibanaPort:-5601}"
    platform: ${elasticAgentPlatform:-linux/amd64}
    volumes:
      - "${elasticAgentConfigFile}:/usr/share/elastic-agent/elastic-agent.yml"
