version: '2.3'
services:
  elastic-agent:
    image: docker.elastic.co/beats/elastic-agent${elasticAgentDockerImageSuffix}:${elasticAgentTag:-7.10-SNAPSHOT}
    container_name: ${elasticAgentContainerName}
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
    environment:
      - "KIBANA_HOST=http://${kibanaHost:-kibana}:${kibanaPort:-5601}"
    volumes:
      - "${elasticAgentConfigFile}:/usr/share/elastic-agent/elastic-agent.yml"
