version: '2.4'
services:
  kibana:
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=changeme
    healthcheck:
      test: ["CMD-SHELL", "curl -u admin:changeme -s http://localhost:5601/api/status | grep -q 'All services are available'"]
      retries: 60
      interval: 10s
    image: "docker.elastic.co/kibana/kibana:${kibanaTag:-8.6.2-7c4539d9-SNAPSHOT}"
    ports:
      - "5601:5601"
