version: '2.4'
services:
  kibana:
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=changeme
    healthcheck:
      test: "curl -f http://localhost:5601/login | grep kbn-injected-metadata 2>&1 >/dev/null"
      retries: 600
      interval: 1s
    image: "docker.elastic.co/kibana/kibana:${kibanaTag:-8.5.4-53cae6e0-SNAPSHOT}"
    ports:
      - "5601:5601"
