version: '2.3'
services:
  metricbeat:
    command: [
      "metricbeat", "-e",
      "-E", "logging.level=${logLevel}",
      "-E", "setup.ilm.rollover_alias=${indexName}",
      "-E", "output.elasticsearch.hosts=http://elasticsearch:9200",
      "-E", "output.elasticsearch.password=changeme",
      "-E", "output.elasticsearch.username=elastic",
      "-E", "setup.kibana.host=http://kibana:5601",
      "-E", "setup.kibana.password=changeme",
      "-E", "setup.kibana.username=elastic",
    ]
    environment:
      - BEAT_STRICT_PERMS=${beatStricPerms:-false}
    image: "docker.elastic.co/beats/metricbeat:${metricbeatTag:-7.10-SNAPSHOT}"
    labels:
      co.elastic.logs/module: "${serviceName}"
    volumes:
      - "${metricbeatConfigFile}:/usr/share/metricbeat/metricbeat.yml"
